### ISSUE TITLE
Wrong packing of "Range" in record extension

### ISSUE THREAD

**Issue by jomihaka** [tych0/xcffib#89] opened 2018-03-08 14:57 UTC
The generator produces incorrect packing for the Range structure defined in record extension:

``` python
    def pack(self):
        buf = six.BytesIO()
        buf.write(struct.pack("=BB", self.client_started, self.client_died))
        buf.write(self.core_requests.pack() if hasattr(self.core_requests, "pack") else Range8.synthetic(*self.core_requests).pack())
        buf.write(self.core_replies.pack() if hasattr(self.core_replies, "pack") else Range8.synthetic(*self.core_replies).pack())
        buf.write(self.ext_requests.pack() if hasattr(self.ext_requests, "pack") else ExtRange.synthetic(*self.ext_requests).pack())
        buf.write(self.ext_replies.pack() if hasattr(self.ext_replies, "pack") else ExtRange.synthetic(*self.ext_replies).pack())
        buf.write(self.delivered_events.pack() if hasattr(self.delivered_events, "pack") else Range8.synthetic(*self.delivered_events).pack())
        buf.write(self.device_events.pack() if hasattr(self.device_events, "pack") else Range8.synthetic(*self.device_events).pack())
        buf.write(self.errors.pack() if hasattr(self.errors, "pack") else Range8.synthetic(*self.errors).pack())
        return buf.getvalue()
```
Range structure is defined in xcb/record.xml as follows:
``` xml
    <struct name="Range">
	<field type="Range8" name="core_requests" />
	<field type="Range8" name="core_replies" />
	<field type="ExtRange" name="ext_requests" />
	<field type="ExtRange" name="ext_replies" />
	<field type="Range8" name="delivered_events" />
	<field type="Range8" name="device_events" />
	<field type="Range8" name="errors" />
	<field type="BOOL" name="client_started" />
	<field type="BOOL" name="client_died" />
    </struct>

```
This means that client_started and client_died are incorrectly in front of the structure, instead of being last.

**Comment by tych0** [comment] 2018-03-08 15:14
So it does, thanks. I believe the problem is in mkPackStmts, we really shouldn't partitionEithers there, we should map the generator over the result inline. I'll try and fix it tonight. Thanks for the report!

**Comment by jomihaka** [comment] 2018-09-01 11:14
I got reminded about this today, so I thought reminding you about it, too.

**Comment by amerlyq** [comment] 2021-09-24 03:20
I'm trying to port selfspy repo to XCB and had stumbled on trying to convert create_context semantic to XCB due to this :)
* https://github.com/selfspy/selfspy/blob/master/selfspy/sniff_x.py#L69

Any ideas how to workaround it temporarily, until the original issue in xcffib will be fixed?

**Comment by tych0** [comment] 2021-09-24 13:34
I don't know that it'll ever be fixed unless someone else has time to send a patch; I don't have much time for xcffib these days.

**Comment by amerlyq** [comment] 2021-12-24 13:41
Ok, let's share at least my monkey-patches for Record extension.
I encourage anyone to send them as proper pull request instead:
```python
import xcffib.record as xrec

## HACK: monkey-patched xcffib record ext
def fixed_Range_pack(self):
    buf = __import__("six").BytesIO()
    add = lambda m, t: buf.write(
        m.pack() if hasattr(m, "pack") else t.synthetic(*m).pack()
    )
    add(self.core_requests, xrec.Range8)
    add(self.core_replies, xrec.Range8)
    add(self.ext_requests, xrec.ExtRange)
    add(self.ext_replies, xrec.ExtRange)
    add(self.delivered_events, xrec.Range8)
    add(self.device_events, xrec.Range8)
    add(self.errors, xrec.Range8)
    buf.write(__import__("struct").pack("=BB", self.client_started, self.client_died))
    return buf.getvalue()


def fixed_EnableContextReply_init(self, unpacker):
    if isinstance(unpacker, xcffib.Protobj):
        unpacker = xcffib.MemoryUnpacker(unpacker.pack())
    xcffib.Reply.__init__(self, unpacker)
    base = unpacker.offset
    (
        self.category,
        self.element_header,
        self.client_swapped,
        self.xid_base,
        self.server_time,
        self.rec_sequence_num,
    ) = unpacker.unpack("xB2x4xBB2xIII8x")
    self.data = unpacker.buf[unpacker.offset : unpacker.offset + self.length * 4]
    unpacker.offset += len(self.data)
    self.bufsize = unpacker.offset - base


## TEMP:HACK:PERF: monkey-patching broken functions BET:NEED: fix upstream
xrec.Range.pack = fixed_Range_pack
xrec.EnableContextReply.__init__ = fixed_EnableContextReply_init
```

**Closed** 2023-09-07 01:56 UTC
