### ISSUE TITLE
API question: how to create a color for xcffib.render.renderExtension.FillRectangles()?

### ISSUE THREAD

**Issue by AndreasHoenen** [tych0/xcffib#55] opened 2015-10-09 12:11 UTC
`xcffib` seems to deviate from `xpyb` regarding the `color` parameter of `xcffib.render.renderExtension.FillRectangles()`: using a color tuple as parameter results in:
`AttributeError: 'tuple' object has no attribute 'pack'`

How to create a color that `xcffib` can handle? (I have stumbled about this question when porting the "Full Example" from http://xcb.freedesktop.org/XcbPythonBinding/)

**Comment by tych0** [comment] 2015-10-09 14:56
On Fri, Oct 09, 2015 at 05:11:34AM -0700, AndreasHoenen wrote:
> `xcffib` seems to deviate from `xpyb` regarding the `color` parameter of `xcffib.render.renderExtension.FillRectangles()`: using a color tuple as parameter results in:
> `AttributeError: 'tuple' object has no attribute 'pack'`

Thanks for the report. Looks like Iterator did more than we initially
thought, which is why things are breaking for you now.

> How to create a color that `xcffib` can handle? (I have stumbled about this question when porting the "Full Example" from http://xcb.freedesktop.org/XcbPythonBinding/)

If you construct the rectangles directly it should work, something
like (untested):

```
rects = [xproto.RECTANGLE.synthetic(x=..., y=..., width=..., height...), ...]
FillRectangle(..., rects=rects)
```

Although you're right, this should be supported as is. I'll see about
getting an implementation this weekend.

**Comment by jakeogh** [comment] 2015-10-21 05:47
I also tried to port the xcb example: https://gist.github.com/jakeogh/6be38098deda85f48c72

svig helped sort out the color (I think, as you can see it still does not work).

However bad my attempt, it seems to have exposed a unhanded exception, __getitem__ in OffsetMap() has offset=140 and things={}

**Comment by tych0** [comment] 2015-10-23 02:01
It just occurred to me this is probably a dupe of #56 (or rather, both of these are a dupe of whatever issue was originally fixed by that commit, although I can't seem to find it now). If you rebuild xcffib from source with xcb-types also from source, you'll probably avoid this error.

Let me know if you want and I can tag a 0.3.7 and upload a fixed version to pypi.

**Comment by kdienes** [comment] 2015-10-26 02:23
This is working for me in the pre-0.3.7 with the fix for #56 applied:

self.render.FillRectanglesChecked(
            xcb.render.PictOp.Src,
            v_picture,
            xcb.render.COLOR.synthetic(red=0x1111, green=0x1111, blue=0x1111, alpha=0xffff),
            [ xcb.xproto.RECTANGLE.synthetic(x=0, y=0, width=100, height=height) ]).check()

**Comment by jakeogh** [comment] 2015-10-26 03:10
Confirmed, after rebuilding latest xcffib and xcb-types my example executes as well. Thanks.

**Closed** 2015-10-31 12:59 UTC

**Comment by tych0** [comment] 2015-10-31 13:00
Looks like there was some other API incompatibilities as well (missing length field from some requests) even after I fixed the packing problem described in the issue. In any case, with the fixes I've just pushed, you can run a copy pasted version of the example (with `s/xcb/xccfib/g` of course).

I couldn't find `xcb.XA_WM_NAME` or similar anywhere, so I'm not sure where those come from or how to generate them.

**Comment by kdienes** [comment] 2015-10-31 14:11
I might be misunderstanding, but if I'm not, you're already generating those atoms as xcffib.xproto.Atom.WM_NAME and similar.

**Comment by tych0** [comment] 2015-10-31 16:20
On Sat, Oct 31, 2015 at 07:11:13AM -0700, Klee Dienes wrote:
> I might be misunderstanding, but if I'm not, you're already generating those atoms as xcffib.xproto.Atom.WM_NAME and similar.

Yeah, the example has something called xcb.XA_WM_NAME. I think those
just didn't ever exist, as near as I can tell.

**Comment by kdienes** [comment] 2015-10-31 16:40
Oh, I get it now.  Sorry about that.
